---
server:
    install: '1'
    packages: [imagemagick, npm, unzip]
    timezone: Europe/Berlin
    locale: de_DE.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: default, ip: 192.160.12.53, memory: '512', sharedfolder: ./, useVagrantCloud: '0', syncType: '0' }
apache:
    install: '1'
    docroot: /vagrant
    servername: local.pim.buehner-kalender.de
mysql:
    install: '1'
    root_password: ''
    database: db
    user: user
    password: pass
    dump: ''
php:
    install: '1'
    upload_max_size: '20M'
    max_execution_time: 240
    memory_limit: '256M'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-curl, php5-imagick, php5-gd, php5-mysql]
xdebug:
    install: '1'
composer:
    install: '1'

